apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-recreate-deployment
spec:
  strategy: 
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: nginx-recreate
  template:
    metadata:
      labels:
        app: nginx-recreate
    spec:
      containers:
      - name: nginx-recreate-container
        image: nginx
