apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod # name of the pod, it will be displayed when you run 'kubectl get pods'
  labels:
   pod: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
