apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  template:
    metadata:
      labels:
        pod: nginx-pod-label
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      pod: nginx-pod-label

    


